[package]
name = "day01"
version = "0.1.0"
authors = ["Nicolas Gonzalez <Nicolas.Gonzalez@insa-rennes.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
